name: publish
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'
    - name: Extract version from release tag
      id: extract_version
      run: |
        version=$(echo "${GITHUB_REF#refs/tags/}")
        echo "VERSION=$version" >> $GITHUB_ENV
    - name: Update SBT version in build.sbt
      run: |
        sed -i "s/ThisBuild \/ version := .*/ThisBuild \/ version := \"$VERSION\"/" build.sbt
    - name: Compile
      run: sbt compile
    - name: Publish
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
      run: sbt publish