name: publish
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'
    - name: Compile
      run: sbt compile
    - name: Publish
      run: sbt publish