name: publish
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v4
      with:
        distribution: 'adopt'
        java-version: '21'
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1    
    - name: Extract version from release tag
      id: extract_version
      run: |
        version=$(echo "${GITHUB_REF#refs/tags/}")
        echo "VERSION=$version" >> $GITHUB_ENV
    - name: Update SBT version in build.sbt
      run: |
        sed -i "s/ThisBuild \/ version := .*/ThisBuild \/ version := \"$VERSION\"/" build.sbt
    - name: Compile
      run: sbt +compile
    - name: Import GPG key
      # Pin action to commit hash for security (v6.3.0)
      uses: crazy-max/ghaction-import-gpg@e89d40939c28e39f97cf32126055eeae86ba74ec 
      with:
        gpg_private_key: ${{ secrets.PGP_SECRET }}
        passphrase: ${{ secrets.PGP_PASSPHRASE }}
        # Optional: Use if your key is not the default in the secret
        # key_id: ${{ secrets.PGP_KEY_ID }} 
    - name: Publish
      env:
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        # Provide passphrase to sbt-pgp
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }} 
      run: sbt +publishSigned